# HomePage FrontEnd
_homepage:
    path:     /
    defaults: { _controller: EcommerceBundle:Product:index }
#Search Features
_search:
    path: /search
    defaults: {_controller: EcommerceBundle:Product:search }

