_homepage:
    path:     /
    defaults: { _controller: EcommerceBundle:Product:index }


#ROUTE LINK TO PRODUCTS FEATURES
_product:
   path:  /product/{id}
   defaults : { _controller: EcommerceBundle:Product:single }
   requirements:
       id: \d+
_productAdd:
    path : /product/add
    defaults : {_controller: EcommerceBundle:Product:add}

#ROUTE LINK TO CART FEATURES
_cart:
    path : /cart
    defaults : { _controller: EcommerceBundle:Cart:index}
_delivery:
    path: /delivery
    defaults : { _controller : EcommerceBundle:Cart:delivery}

_validate:
    path: /validate
    defaults : { _controller : EcommerceBundle:Cart:validate}
