services:
    tva:
        class: Ecommerce\EcommerceBundle\Twig\Extention\TvaExtention
        tags:
            - { name: twig.extension }
    amoutTva:
        class: Ecommerce\EcommerceBundle\Twig\Extention\TvaAmount
        tags:
            - { name: twig.extension }

    redirection_listener:
        class: Ecommerce\EcommerceBundle\Listener\RedirectionListener
        arguments: ['@service_container', '@session']
        tags:
            - { name : kernel.event_listener, event: kernel.request, method: onKernelRequest }
    setNewRef:
        class: Ecommerce\EcommerceBundle\Services\GetReference
        arguments : ['@security.context', '@doctrine.orm.entity_manager']