services:
    tva:
        class: Ecommerce\EcommerceBundle\Twig\Extention\TvaExtention
        tags:
            - { name: twig.extension }
    amoutTva:
        class: Ecommerce\EcommerceBundle\Twig\Extention\TvaAmount
        tags:
            - { name: twig.extension }
