<?php

namespace Users\UsersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserAdressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAdressRepository extends EntityRepository
{

    public function getIdUser($id){
            $qb = $this->createQueryBuilder('a')
                ->select('a.user')
                ->where('a.id = :id')
                ->setParameter('id', $id) ;
            return $qb->getQuery()->getResult() ;
    }
}
