users:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /users
pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /pages

ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /
admin:
    resource : "@EcommerceBundle/Resources/config/routing_admin.yml"
    prefix: /admin