# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    success.login.handler:
        class: Users\UsersBundle\Handler\AuthentificationSuccessHandler
        arguments: ['@router','@security.authorization_checker']

    app.form.registration:
        class: Users\UsersBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    failure.login.handler:
        class : Users\UsersBundle\Handler\AuthentificationFailureHandler
        arguments:  ['@http_kernel', '@security.http_utils', {}, '@logger']