_homepage_admin:
    path:     /
    defaults: { _controller: EcommerceBundle:Admin:index }
_catalog:
    path: /Catalog
    defaults: { _controller: EcommerceBundle:CatalogAdmin:index}
#Page AdminRouting
page_admin:
    resource : "@PagesBundle/Resources/config/routing/routing_admin.yml"
    prefix: /Page
pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /Pages

modules_admin:
    resource: "@PagesBundle/Resources/config/routing/routing_module.yml"
    prefix:   /Modules