_homepage_admin:
    path:     /
    defaults: { _controller: EcommerceBundle:Admin:index }
_catalog:
    path: /Catalog
    defaults: { _controller: EcommerceBundle:CatalogAdmin:index}

_pages:
    path: /Page
    defaults: {_controller :EcommerceBundle:PageAdmin:index}