# ROUTE LINKED TO CART FEATURES
_cart:
    path : /
    defaults : { _controller: EcommerceBundle:Cart:index}

_delivery:
    path: /delivery
    defaults : { _controller : EcommerceBundle:Cart:delivery}

_validate:
    path: /validate
    defaults : { _controller : EcommerceBundle:Cart:validate}
_add:
    path: /add/{id}
    defaults:   {_controller : EcommerceBundle:Cart:add}
_delete:
    path: /delete/{id}
    defaults: { _controller : EcommerceBundle:Cart:del}