fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix : /

#Search Features
_invoic_user:
    path: /invoic
    defaults: {_controller: UsersBundle:User:invoic }

_invoic_pdf:
    path: /invoic/PDF/{id}/{token}
    defaults : {_controller :UsersBundle:User:invoicPdf}
    requirements:
        id: \d+

_invoic_html:
    path: /invoic/HTML/{id}/{token}
    defaults : {_controller :UsersBundle:User:invoicHtml}
    requirements:
        id: \d+