<?php

namespace Ecommerce\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends EntityRepository
{

    public function getInvoicByUser($user){
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.user = :user')
                ->andWhere('u.validate = 1')
                ->andWhere('u.reference != 0')
                ->orderBy('u.id')
                ->setParameter('user', $user);

        return $qb->getQuery()->getResult() ;
    }
}
