<?php

namespace Ecommerce\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends EntityRepository
{
    /**
     * Query : Get All Product according to the Category
     * @param $idCategory
     * @return array
     */
    public function getAllByCategorie($idCategory){
        $qb = $this->createQueryBuilder('p')
                ->select('p')
                ->where('p.category = :idCategory')
                ->andWhere('p.available = 1')
                ->orderBy('p.id')
                ->setParameter('idCategory', $idCategory) ;

        return $qb->getQuery()->getResult() ;
    }

    /**
     * Get the products search
     * @param $value
     * @return array
     */
    public function search($value){
        $qb = $this->createQueryBuilder('p')
                    ->select('p')
                    ->where('p.name like :value')
                    ->andWhere('p.available = 1')
                    ->orderBy('p.id')
                    ->setParameter('value','%'.$value.'%');

        return $qb->getQuery()->getResult() ;
    }

    /**
     * @param $array
     * @return array
     */
    public function findArray($array){
        $qb = $this->createQueryBuilder('p')
                    ->select('p')
                    ->where('p.id IN (:array)')
                    ->setParameter('array',$array);

        return $qb->getQuery()->getResult() ;
    }
}
