<?php

namespace Ecommerce\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends EntityRepository
{
    /**
     * Query : Get All Product according to the Category
     * @param $idCategory
     * @return array
     */
    public function getAllByCategorie($idCategory){
        $qb = $this->createQueryBuilder('p')
                ->select('p')
                ->where('p.category = :idCategory')
                ->orderBy('p.id')
                ->setParameter('idCategory', $idCategory) ;

        return $qb->getQuery()->getResult() ;
    }

    public function search($value){

    }
}
